# Generated by Django 3.0.2 on 2020-06-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200625_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='up_date',
            new_name='pub_date',
        ),
    ]
